replicaCount: 1

namespace: k8s-project

image0:
  name: rabbitmq
  repository: rabbitmq
  pullPolicy: Always
  tag: "3-management"

image1:
  name: consumer
  repository: yidgar11/consumer
  pullPolicy: Always
  tag: "1.0"

image2:
  name: producer
  repository: yidgar11/producer
  pullPolicy: Always
  tag: "1.0"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podLabels: {}

service:
  name: rabbitmq-service
  mainName: rabbitmq-main
  mgmtName: rabbitmq-mgmt
  type: ClusterIP
  protocol: TCP
  rabbitmqMainPort: 5672
  rabbitmqMainTargetPort: 5672
  rabbitmqMgmtPort: 15672
  rabbitmqMgmtTargetPort: 15672


ingress:
  enabled: false
  hosts:
    - host: k8sproject
      paths:
        - path: /
          pathType: ImplementationSpecific


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

